name: My first github action 
on: [push]
jobs: 
  build-project: 
    runs-on: ubuntu-latest
    steps: 
      - name: install node dependecies
        run: npm install
      - name: build the projejct
        run: npm run build